# Generated by Django 2.1.2 on 2018-10-18 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appmanager', '0003_auto_20181018_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllPledges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pledge_amount', models.DecimalField(decimal_places=2, max_digits=1000000)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=1000000)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=1000000)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='appmanager.members')),
            ],
            options={
                'verbose_name_plural': 'pledges',
            },
        ),
        migrations.CreateModel(
            name='PledgePayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=1000000)),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledge_payments', to='pledgesapp.AllPledges')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PledgePurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(max_length=200)),
                ('beneficiary', models.CharField(max_length=200)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=1000000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='allpledges',
            name='purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_pledges', to='pledgesapp.PledgePurpose'),
        ),
    ]
