# Generated by Django 2.1.2 on 2018-10-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledgesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pledgepayments',
            options={'verbose_name_plural': 'Pledge payments'},
        ),
        migrations.AlterField(
            model_name='pledgepurpose',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000000, null=True),
        ),
    ]
