# Generated by Django 2.1.2 on 2018-10-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledgesapp', '0002_auto_20181018_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledgepurpose',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
