# Generated by Django 2.1.2 on 2018-10-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledgesapp', '0004_auto_20181018_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpledges',
            name='initial_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000000, null=True),
        ),
    ]
