# Generated by Django 2.1.2 on 2018-10-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pledgesapp', '0006_pledgepayments_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledgepayments',
            name='balance',
        ),
    ]
