# Generated by Django 2.1.2 on 2018-10-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pledgesapp', '0007_remove_pledgepayments_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledgepayments',
            old_name='amount',
            new_name='amount_paid',
        ),
    ]
