# Generated by Django 2.1.2 on 2018-10-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loansapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='balance',
            field=models.FloatField(blank=True, max_length=1000000, null=True),
        ),
    ]
