# Generated by Django 2.1.2 on 2018-10-16 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loansapp', '0002_auto_20181016_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount_paid', models.FloatField(max_length=1000000)),
                ('balance', models.FloatField(blank=True, max_length=1000000, null=True)),
            ],
            options={
                'verbose_name_plural': 'payments',
            },
        ),
        migrations.AlterModelOptions(
            name='loans',
            options={'verbose_name_plural': 'loans'},
        ),
        migrations.AddField(
            model_name='payments',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan+', to='loansapp.loans'),
        ),
    ]
