# Generated by Django 2.1.2 on 2018-10-16 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loansapp', '0003_auto_20181016_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments+', to='loansapp.loans'),
        ),
    ]
