# Generated by Django 2.1.2 on 2018-10-17 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loansapp', '0006_auto_20181016_2029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name_plural': 'loan_payments'},
        ),
    ]
