# Generated by Django 2.1.2 on 2018-10-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loansapp', '0007_auto_20181017_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interests',
            name='interest_accrued',
            field=models.DecimalField(decimal_places=2, max_digits=1000000),
        ),
        migrations.AlterField(
            model_name='loans',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=1000000),
        ),
        migrations.AlterField(
            model_name='loans',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=1000000),
        ),
        migrations.AlterField(
            model_name='payments',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000000, null=True),
        ),
    ]
