# Generated by Django 2.1.2 on 2018-10-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loansapp', '0008_auto_20181018_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name_plural': 'Loan payments'},
        ),
    ]
