# Generated by Django 2.1.2 on 2018-10-17 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGMBalances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('balance', models.FloatField(max_length=1000000)),
                ('year', models.CharField(max_length=4)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_AGM_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AGM_balances',
            },
        ),
        migrations.CreateModel(
            name='AGMContributions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount_paid', models.FloatField(max_length=1000000)),
                ('year', models.CharField(max_length=4)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_AGM', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AGM_payments',
            },
        ),
    ]
